### ISSUE TITLE
Github action replace monorepo references in package.json for specific versions

### ISSUE THREAD

**Issue by Hookyns** [ionic-solidjs/ionic-solidjs#20]
This breaks the local development. After install you'll get the npm version of the package instead of the local workspace one.

![image](https://github.com/ionic-solidjs/ionic-solidjs/assets/2551259/fca5782a-a798-4926-ada3-51611ca6e732)

**Comment by spion** [comment]
Isn't there a way to force bun to use workspace dependencies here?

**Comment by spion** [comment]
The only reason I started with `bun` is because it offers a non-tedious way to run TS scripts without the arduous compile step. If we have a replacement for that that isn't tedious (maybe `tsx`?) I think `npm` is probably a fine package management default that will (AFAIK) autolink workspace dependencies

**Comment by Hookyns** [comment]
You can use `bun` just as a runtime instead of `node` and use `npm` or `pnpm` as a package manager. 
I prefer `pnpm` because it has better support for monorepos (workspaces) and it handles node_modules much much better.

**Comment by spion** [comment]
`pnpm` is my preference too normally.

**Comment by spion** [comment]
This shold now be fixed with `pnpm` and `link-workspace-packages=true` in `.npmrc`
